# Generated by Django 3.1.5 on 2021-02-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='usersss',
        ),
    ]
