# Generated by Django 3.1.5 on 2021-02-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0003_auto_20210205_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usersss',
            new_name='user',
        ),
    ]
