# Generated by Django 3.1.5 on 2021-02-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0005_auto_20210205_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
