# Generated by Django 3.1.5 on 2021-02-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0009_auto_20210205_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='quanity',
        ),
        migrations.AddField(
            model_name='user',
            name='quanity1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='quanity2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='quanity3',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='quanity4',
            field=models.IntegerField(default=4),
        ),
    ]
