# Generated by Django 3.1.5 on 2021-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0012_auto_20210206_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='release.Items'),
        ),
    ]
