# Generated by Django 3.1.5 on 2021-02-07 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0015_auto_20210206_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='release.shipping_info'),
        ),
    ]
