# Generated by Django 3.1.5 on 2021-02-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0004_auto_20210205_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='ipaddress',
        ),
    ]
