# Generated by Django 3.1.5 on 2021-02-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0008_auto_20210205_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='item',
        ),
        migrations.AddField(
            model_name='user',
            name='item',
            field=models.ManyToManyField(to='release.Items'),
        ),
    ]
